---
title: "p8105_hw2_tp2806"
author: "Tejashree Prakash"
date: 2025-09-29
output: github_document
---

```{r setup, include=FALSE}
#Load libraries and data
library(tidyverse)
```

```{r}
#Download and clean pols data
pols =
  read_csv("data/fivethirtyeight_datasets/pols-month.csv") %>%
  separate(mon, into = c("year", "month", "day"), sep = "-", convert = TRUE) %>%
  mutate(month = month.name[month]) %>% #Convert numbers to month names 
  mutate(president = case_when( #Create case to show gop or dem president 
    prez_gop == 1 ~ "gop",
    prez_dem == 1 ~ "dem"
  )) %>%
  select(-prez_dem, -prez_gop, -day)

#Download and clean snp data 
snp = 
  read_csv("data/fivethirtyeight_datasets/snp.csv") %>%
  separate(date, into = c("year", "month", "day"), sep = "/", convert = TRUE) %>%
  mutate(month = month.name[month]) %>%
  select(year, month, close, -day)

#Download and clean unemployment data
unemployment = 
  read_csv("data/fivethirtyeight_datasets/unemployment.csv") %>%
  pivot_longer(
    cols = Jan:Dec,
    names_to = "month",
    values_to = "unemployment_percentage"
  ) 

still: change abbreviated months to full name, makes sure all columns have same capitalization 
  
```


year, month, and day

